export const DEFAULT_TEXT = 'Upload your own SVGs to create\n' +
  'text overlay in existing files,\n' +
  'Or use this default SVG as your canvas. \n' +
  'Change font size, font style and more'

// Minimal metadata needed to locate and attribute fonts
export const FONTS = {
  RoutedGothic: {
    filename: 'RoutedGothic', originalURL: 'https://github.com/dse/routed-gothic'
  },
  ReliefRegular: {
    filename: 'Relief/ReliefSingleLine-Regular', originalURL: 'https://github.com/isdat-type/Relief-SingleLine'
  },
  EMSAllure: { filename: 'EMS/EMSAllure', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSAllureSmooth: { filename: 'Cutlings/EMS_Allure_Smooth', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  EMSBird: { filename: 'EMS/EMSBird', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSBirdSwashCaps: { filename: 'EMS/EMSBirdSwashCaps', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSBrush: { filename: 'EMS/EMSBrush', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSCapitol: { filename: 'EMS/EMSCapitol', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSCasualHand: { filename: 'EMS/EMSCasualHand', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSDecorousScript: { filename: 'EMS/EMSDecorousScript', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSDelight: { filename: 'EMS/EMSDelight', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSDelightSwashCaps: { filename: 'EMS/EMSDelightSwashCaps', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSElfin: { filename: 'EMS/EMSElfin', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSElfinSmooth: { filename: 'Cutlings/EMS_Elfin_Smooth', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  EMSFelix: { filename: 'EMS/EMSFelix', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSHerculean: { filename: 'EMS/EMSHerculean', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSInvite: { filename: 'EMS/EMSInvite', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSLeague: { filename: 'EMS/EMSLeague', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSLittlePrincess: { filename: 'EMS/EMSLittlePrincess', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSMistyNight: { filename: 'EMS/EMSMistyNight', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSNeato: { filename: 'EMS/EMSNeato', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSNixish: { filename: 'EMS/EMSNixish', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSNixishItalic: { filename: 'EMS/EMSNixishItalic', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSOsmotron: { filename: 'EMS/EMSOsmotron', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSPancakes: { filename: 'EMS/EMSPancakes', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSPepita: { filename: 'EMS/EMSPepita', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSQwandry: { filename: 'EMS/EMSQwandry', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSReadability: { filename: 'EMS/EMSReadability', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSReadabilityItalic: { filename: 'EMS/EMSReadabilityItalic', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSSociety: { filename: 'EMS/EMSSociety', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSSpaceRocks: { filename: 'EMS/EMSSpaceRocks', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSSwiss: { filename: 'EMS/EMSSwiss', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  EMSTech: { filename: 'EMS/EMSTech', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyAstrology: { filename: 'Hershey/HersheyAstrology', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyGothEnglish: { filename: 'Hershey/HersheyGothEnglish', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyGothGerman: { filename: 'Hershey/HersheyGothGerman', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyGothItalian: { filename: 'Hershey/HersheyGothItalian', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySans1: { filename: 'Hershey/HersheySans1', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySansMed: { filename: 'Hershey/HersheySansMed', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyScript1: { filename: 'Hershey/HersheyScript1', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyScript1Smooth: { filename: 'Cutlings/HersheyScript1smooth', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  HersheyScriptMed: { filename: 'Hershey/HersheyScriptMed', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySerifBold: { filename: 'Hershey/HersheySerifBold', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySerifBoldItalic: { filename: 'Hershey/HersheySerifBoldItalic', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySerifMed: { filename: 'Hershey/HersheySerifMed', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheySerifMedItalic: { filename: 'Hershey/HersheySerifMedItalic', originalURL: 'https://gitlab.com/oskay/svg-fonts' },
  HersheyCyrillic: { filename: 'Hershey/HersheyCyrillic', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  'HersheyGreek-1-stroke': { filename: 'Hershey/HersheyGreek1stroke', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyGreekmedium: { filename: 'Hershey/HersheyGreekmedium', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyJapanese: { filename: 'Hershey/HersheyJapanese', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyMarkers: { filename: 'Hershey/HersheyMarkers', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  'HersheyMath(lower)': { filename: 'Hershey/HersheyMath(lower)', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  'HersheyMath(upper)': { filename: 'Hershey/HersheyMath(upper)', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyMeteorology: { filename: 'Hershey/HersheyMeteorology', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheyMusic: { filename: 'Hershey/HersheyMusic', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheySansbold: { filename: 'Hershey/HersheySansbold', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  'HersheyScript-1-stroke(alt)': { filename: 'Hershey/HersheyScript1-stroke(alt)', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  HersheySymbolic: { filename: 'Hershey/HersheySymbolic', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  ReliefOrnament: { filename: 'Relief/ReliefSingleLineOrnament-Regular', originalURL: 'https://github.com/isdat-type/Relief-SingleLine' },
  CutlingsSingularis: { filename: 'Cutlings/CutlingsSingularis', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  CutlingsDualis: { filename: 'Cutlings/CutlingsDualis', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  CutlingsPluralis: { filename: 'Cutlings/CutlingsPluralis', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  CutlingsGeometric: { filename: 'Cutlings/CutlingsGeometric', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  CutlingsGeometricRound: { filename: 'Cutlings/CutlingsGeometricRound', originalURL: 'http://cutlings.wasbo.net/products-fonts/' },
  ShriinivasCustom: { filename: 'Shriinivas/Custom-Script', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  ShriinivasSquareItalic: { filename: 'Shriinivas/Custom-SquareItalic', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
  ShriinivasSquareNormal: { filename: 'Shriinivas/Custom-SquareNormal', originalURL: 'https://github.com/Shriinivas/inkscapestrokefont' },
}

